#!/bin/bash
#
# This script parses all files generated by DxDiag with .txt extension and produce CSV file
# ready for import to excel for further analysis.
#
#

# print CSV header
echo "Incident, Machine, CPU, Chipset, IPC Model, IPC Brand, Graphics, OS, OS Type, RAM, Frame Grabber"

# parse all files with .txt extension
for f in *.txt; do

    incident=$f # take TXT file name as incident ID

    # find CPU model, OS, memory and system model
    # between System Information and DxDiag Notes
    n=`cat "$f" | grep -n 'DxDiag Notes' | cut -f1 -d:`
    if [[ -z $n ]]; then
        echo "failure: $n"
        exit
    fi

    machine=`cat "$f" | head -n $n | grep 'Machine name' | awk 'BEGIN {FS=":"}{print $2}' | xargs | tr -d "\r" | tr -d "\n" | tr -d ,`
    cpu=`cat "$f" | head -n $n | grep 'Processor' | awk 'BEGIN {FS=":"}{print $2}' | xargs | tr -d "\r" | tr -d "\n" | tr -d ,`
    os=`cat "$f" | head -n $n | grep 'Operating System' | awk 'BEGIN {FS=":"}{print $2}' | xargs | tr -d "\r" | tr -d "\n" | tr -d ,`

    maker=`cat "$f" | head -n $n | grep 'System Manufacturer' | awk 'BEGIN {FS=":"}{print $2}' | xargs | tr -d "\r" | tr -d "\n" | tr -d ,`
    sysmodel=`cat "$f" | head -n $n | grep 'System Model' | awk 'BEGIN {FS=":"}{print $2}' | xargs | tr -d "\r" | tr -d "\n" | tr -d ,`
    dram=`cat "$f" | head -n $n | grep 'Memory' | grep -v 'Available OS Memory' | awk 'BEGIN {FS=":"}{print $2}' | awk '{print $1}' | tr -d ,`

    # find graphics card model at "Display Devices"
    n=`cat "$f" | grep -n 'Display Devices' | cut -f1 -d:`
    n=$((n+2))
    #BUG here: head "$f"
    graphics=`cat "$f" | head -n $n "$f" | tail -n 1| grep 'Card name' | awk 'BEGIN{FS=":"}{print $2}' | xargs | tr -d "\r" | tr -d "\n" | tr -d ,` 

    # find AVerMedia frame grabbers at "Sound Capture Devices"
    n=`cat "$f" | grep -n 'Sound Capture Devices' | cut -f1 -d:`
    e=`cat "$f" | grep -n 'DirectInput Devices' | cut -f1 -d:`
    l=$((e-n))
    # WARNING: only list first AVerMedia card.
    fg=`cat "$f" | head -n $e | tail -n $l | grep AVerMedia | head -n 1 | awk 'BEGIN{FS=":"}{print $2}'`

    # post-processing
    # Operating System
    if [[ "$os" == *"Windows 10"* ]]; then
        ostype="10"
    elif [[ "$os" == *"Windows 7"* ]]; then
        ostype="7"
    elif [[ "$os" == *"Windows 8"* ]]; then
        ostype="8"
    elif [[ "$os" == *"Windows Embedded"* ]]; then
        ostype="Embedded"
    elif [[ "$os" == *"Windows Server 2012"* ]]; then
        ostype="Server 2012"
    elif [[ "$os" == *"Windows Server 2008"* ]]; then
        ostype="Server 2008"
    else
        ostype="Others"
    fi

    # post-processing
    # system manufacturer
    if [[ "$maker" == *"Gigabyte"* ]]; then
        makershort="Gigabyte"
    elif [[ "$maker" == *"Dell"* ]]; then
        makershort="Dell"
    elif [[ "$maker" == *"Supermicro"* ]]; then
        makershort="SuperMicro"
    elif [[ "$maker" == *"Huawei"* ]]; then
        makershort="Huawei"
    elif [[ "$maker" == *"ASUS"* ]]; then
        makershort="ASUS"
    elif [[ "$maker" == *"Hewlett-Packard"* ]]; then
        makershort="HP"
    elif [[ "$maker" == *"HP"* ]]; then
        makershort="HP"
    elif [[ "$maker" == *"MSI"* ]]; then
        makershort="MSI"
    elif [[ "$maker" == *"ADLINK"* ]]; then
        makershort="ADLINK"
    else 
        makershort="Others"
    fi

    # output as CSV format
    echo "${incident}" "," "${machine}" "," "${cpu}" "," "${chipset}" "," "${maker}" "${sysmodel}" "," "${makershort}" "," "${graphics}" "," "${os}" "," "$ostype" "," "${dram}" "," "${fg}"

    #debug 
    continue
    echo "$incident"
    echo "$cpu"
    echo "$chipset"
    echo "$maker"
    echo "$sysmodel"
    echo "$graphics"
    echo "$os"
    echo "$dram"
    echo

done

